name: Copy Code from Source Repository

on:
  workflow_run:
    workflows:
      - "Copy Code to Target Repository"
    types:
      - completed

jobs:
  copy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code Artifact
        uses: actions/download-artifact@v2
        with:
          name: code-artifact
          path: vijaykumar-jampana/EDP/DBS  # Specify the directory to download the artifact

      - name: Copy Code to Target Location
        run: |
          cp -r vijaykumar-jampana/EDP/DBS vijaykumar-jampana/EDP_UAT/
