name: Test Copy Code
on:
  push:
    branches:
      - main

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python and install Databricks CLI
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Databricks CLI
        run: pip install databricks-cli

