name: Test Copy Code
on:
  push:
    branches:
      - main

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Copy Code to Target Repository
        run: |
          git clone --depth 1 --branch main 'https://github.com/vijaykumar-jampana/EDP_UAT.git' Target
          cp -R ./DBS/. Target/
          cd Target
          git config --local user.email "vijjulearn@gmail.com"
          git config --local user.name "/VijayKumar-Jampana"
          git config --local credential.helper '!f() { echo "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"; }; f' 
          git add .
          git commit -m "Copy code from source repository"
          git push origin main
