name: Test Copy Code 
on:
  push:
    branches:
      - main

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: vijaykumar-jampana/EDP

      - run: |
          cp -r DBS/ vijaykumar-jampana/EDP_UAT
