name: Copy Code from Source Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: vijaykumar-jampana/EDP  # Replace with the correct owner and repository name of the source repository

      - name: Copy Code to Destination Repositories
        run: |
          for repo in EDP_UAT; do
            cp -r DBS/** $repo
          done
